### ISSUE TITLE
Question about corrector type

### ISSUE THREAD

**Issue by nightBrise** [ocelot-collab/ocelot#209]
Hello,
Thanks for your work on this code. I have a question about corrector. In some existing free electron laser devices, the horizontal and vertical corrections are achieved using a same corrector. However, it seems that in the code, only separate Hcor and Vcor can be created. Is there a feature available to use a single corrector for both horizontal and vertical corrections?
Thanks advance for your reply!

**Comment by sergey-tomin** [comment]
Hi,

No, and the reason is following. While it may seem more convenient for simulation purposes, and I understand its usefulness in certain cases. However, Ocelot is also used in the control room for orbit correction, where, in practice, there are always two separate power supplies and two different channels (doocs, epics etc) to control the vertical and horizontal coils even if it is a single physical corrector. That is why to have two object is much more convenient. 
Creating one class for both corrections would pose challenges in the control room. Thus far, I haven't been able to find a solution that satisfies both cases. That's why I give a little more priority to its usage in the control room.

Sergey.

**Comment by nightBrise** [comment]
I understand, thank you for your reply.
